trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '6182441a-a44c-4647-9a12-c8846b43f898'
  imageRepository: 'techsparrowdocker'
  containerRegistry: 'sparrowcontainerregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Sparrow/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        echo "Dockerfile path: $(dockerfilePath)"
        echo "Build sources directory: $(Build.SourcesDirectory)"
        ls -al $(Build.SourcesDirectory)/Sparrow
      displayName: 'Debug: Display file structure'
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(containerRegistry)/$(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
