- task: Docker@2
  inputs:
    containerRegistry: 'sparrowcontainerregistry'
    repository: $(imageRepository)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self
68fa3e36-3e48-46b1-9ff3-248c6f3575df
variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '6182441a-a44c-4647-9a12-c8846b43f898'
  imageRepository: 'techsparrowdocker'
  containerRegistry: 'sparrowcontainerregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Sparrow/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
